// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLEZ1D4M14pw9O11qno-Jmeq8QX2UN3HE',
    appId: '1:841668179533:web:3b41903d0232bd9fb84e04',
    messagingSenderId: '841668179533',
    projectId: 'hatsukoi-f69f3',
    authDomain: 'hatsukoi-f69f3.firebaseapp.com',
    storageBucket: 'hatsukoi-f69f3.appspot.com',
    measurementId: 'G-GFMWG5F0ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdUKT49PkedWMOQfInPS9rv8yz13BbsQ4',
    appId: '1:841668179533:android:c5600093d10275e1b84e04',
    messagingSenderId: '841668179533',
    projectId: 'hatsukoi-f69f3',
    storageBucket: 'hatsukoi-f69f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFXGpwKdggxHT84ACdzm71sNbNiRulIU0',
    appId: '1:841668179533:ios:b5c6b7b5152f0252b84e04',
    messagingSenderId: '841668179533',
    projectId: 'hatsukoi-f69f3',
    storageBucket: 'hatsukoi-f69f3.appspot.com',
    iosClientId: '841668179533-hgp0004e4p916fravcp7ludgmsp8bg72.apps.googleusercontent.com',
    iosBundleId: 'com.example.hatsukoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFXGpwKdggxHT84ACdzm71sNbNiRulIU0',
    appId: '1:841668179533:ios:b5c6b7b5152f0252b84e04',
    messagingSenderId: '841668179533',
    projectId: 'hatsukoi-f69f3',
    storageBucket: 'hatsukoi-f69f3.appspot.com',
    iosClientId: '841668179533-hgp0004e4p916fravcp7ludgmsp8bg72.apps.googleusercontent.com',
    iosBundleId: 'com.example.hatsukoi',
  );
}
